[platformio]
default_envs = lilygo-t-display-s3

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
build_flags =
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=170
  -DTFT_HEIGHT=320
  -DCGRAM_OFFSET=1
  -DTFT_MOSI=13
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=17
  -DTFT_BL=38
  -DTFT_BACKLIGHT_ON=1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=6000000
